### PR TITLE
enh: use public passport dataset

### PR DESCRIPTION
**Pull request by bard**
Closes: #191 

Impact:
- speeds up cold (i.e. no previous passport dataset found on disk) service startup
- removes load on the Passport API
- simplifies code

Missing:
- edge case test (missing passport dump)

### CODE REVIEW

**Review by vacekj — APPROVED** [review]

**Review by boudra — APPROVED** [review]
Awesome!

How up to date is the dump? does passport update it periodically?

**Comment by bard** [comment]
Every 30 minutes if I recall correctly.

**Comment by bard** [comment]
> Awesome!
> 
> How up to date is the dump? does passport update it periodically?

I think this is the PR where the dump was introduced: https://github.com/gitcoinco/passport-scorer/pull/383

**Comment by boudra** [comment]
@bard merging this 🚀

**Pull request merged**
