### PR TITLE
test: matching cap

### LINKED ISSUE #103: Indexer: Matching Cap Integration Test
- Test the matching cap feature of the matches endpoint
- Take into account that you can enable it through the query parameters and the round settings

You can assert that none of the matches returned pass the matching cap

### PR DESCRIPTION
**Pull request by vacekj**
fixes #103

### CODE REVIEW

**Review by boudra — COMMENTED** [review]
we need to test that matchingCap is disabled as well, or is that covered by other tests?

**Comment by vacekj** [comment]
> 

I think that should be covered by the "pure" matching test?

**Comment by vacekj** [comment]
@boudra added a test for disabled matching cap.

**Review by boudra — APPROVED** [review]
🚀

**Review by bhargavaparoksham — APPROVED** [review]

**Pull request merged**
